### ISSUE TITLE
[unicorn] Implement transactions log

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-bestiary#36]
Following the tasks from issue https://github.com/chaoss/grimoirelab/issues/304, the aim of this issue is to implement a transaction log [as we did in SortingHat](https://github.com/chaoss/grimoirelab-sortinghat/issues/220). This log must contain information about the transactions and the database operations which are performed for each transaction.

Taking into account GDPR, we must also store who runs a given transaction, [as we did in SortingHat](https://github.com/chaoss/grimoirelab-sortinghat/issues/241) too.

**Comment by sduenas** [comment]
Closed in #38.

**Comment by sduenas** [comment]
Fixed in #38
