### ISSUE TITLE
[unicorn] Define the database model

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-bestiary#39]
The goal of this issue is to define the database model, following the discussion from issue https://github.com/chaoss/grimoirelab/issues/83.

As a starting point, at least these three main entities have to be defined: **Ecosystems**, **Projects** and **Repositories**. 

This model should support complex hierarchies of sub-projects (`Ecosystem > Project > ... > Project > Repositories`).

---

Note: This issue is a subtask from issue https://github.com/chaoss/grimoirelab/issues/304.

**Comment by mafesan** [comment]
# Bestiary data model definition: Basic entities

We need Bestiary to manage the set of data to be analyzed by GrimoireLab platform. Feedback is more than welcome!

From the [issue](https://github.com/chaoss/grimoirelab/issues/83) describing how this model should be made, there are some assumptions taken:
* Names for **ecosystems** and **projects** might not be unique. This means we will use another unique identifier for these kind of entities.
* A given **project** could belong or not to a given **ecosystem**.

Let's describe the basic entities from Bestiary. The idea is to focus on the single, individual data end-points where the information is retrieved from and define from there the rest of related components.

## Data end-points

They are individual objects identifying in a unique way an end-point from where data can be obtained and processed by GrimoireLab.

These end-points must belong to a **data source** supported by GrimoireLab platform.

Some particular examples of **end-points** would be: a **GitLab repository**, a **Slack channel**, a **mailing list** or a **Meetup group**.

## End-point sets

They are sets of **end-points** which share common characteristics and the data which can be obtained from them. For instance, a group of Git repositories or a group of mailing lists.

Note: A given **end-point** could belong to different **end-point sets**.

## Data sources

Types of data sources supported by GrimoireLab. Every **end-point set** must belong to one of these data sources. These data sources refer to a specific way of obtaining information from the set of data sources.

For instance, an **end-point set** made of GitLab repositories could belong to different **data sources**:

* Git (to get the commit information from those repos).
* GitLab Issues.
* GitLab MRs.

## Projects

A **project** is defined as a group of **end-point sets** (which belong to the corresponding **data sources**) which share a common context.

The projects can also have *n* sub-projects which also have groups of end-point sets.

Note: A given **end-point set** could belong to different **projects** at the same time, to one or any project at all.

## Ecosystems

An **ecosystem** is defined as a set of **projects**. A **project** could belong
to one single **ecosystem**, to different ones or not belonging to anyone.

# Discussion

There are some details to be discussed. Some of them are explained below and others will raise up after the proposal described above.

* Does it make sense to keep the **End-point set** entity? Or **Data end-points** could be directly related to one or many **data sources**?

* Although it does not has direct relation, we should define how configuration parameters are going to be managed. I think this is where **End-point sets** could make sense, as the same configuration or parameters could be applied to them.

* Do we need to define abstract types for the different **Data sources** we support? For instance, this could be applied for validation: for a given data source, the different **end-point sets** could be checked to see if the single **data end-points** forming them are valid in the way the platform expects.

# WIP

I'm currently working on defining and implementing the fields for each of these entities and their relations with Django models.

I made a very basic sketch about the basic entities described above. Please note that it is only a sketch and it does not intend to show accurately the models with all their fields, but a draft example of how the entities could be related with each other.

![bestiary](https://user-images.githubusercontent.com/9032790/76991803-7cc4f380-694a-11ea-8d27-40ab27889477.png)

**Comment by mafesan** [comment]
# Update about Bestiary data model definition

## Discussion follow-up

> Does it make sense to keep the **End-point set** entity? Or **Data end-points** could be directly related to one or many **data sources**?

We decided this **end-point set** entity has sense only when is divided into more sub-entities. As we need where to define the access configuration and the different views we may have for the same data end-point. That's why these new entities have been defined: **access configurations** and **end-point views**. These entities are explained with more detail after this section.

I would like to mark that the **end-point view** entities are the ones which must be related to the corresponding **data source**. A single **data end-point** could have different **end-point views**, and every one of them could be linked to different **data sources** (categories).

> Although it does not has direct relation, we should define how configuration parameters are going to be managed. I think this is where **End-point sets** could make sense, as the same configuration or parameters could be applied to them.

The idea is to distinguish between the configuration used to access the **data end-point** (e.g., a token) and the configuration about which data to get from that end-point (e.g., filtering data from a given date or a particular characteristic from the data).

> Do we need to define abstract types for the different **Data sources** we support? For instance, this could be applied for validation: for a given data source, the different **end-point sets** could be checked to see if the single **data end-points** forming them are valid in the way the platform expects.

I do think we have to define classes coming from the different backends supported by GrimoireLab platform. This way, a given **end-point view** must belong to one of these supported data sources.

---

This is the updated list of entities and its main description:

## Data end-points

They are individual objects identifying in a unique way an end-point from where data can be obtained and processed by GrimoireLab. These end-points must belong to a **data source** supported by GrimoireLab platform.

Some particular examples of **data end-points** would be: a **GitLab repository**, a **Slack channel**, a **mailing list** or a **Meetup group**.

Note: These entities can be shared across different **projects** and **ecosystems**.

## Access configurations

They are objects representing the needed configuration and parameters to access one or
many **data end-points**. This means one configuration object can be shared among many **data end-points**.

## Data sources

Types of data sources supported by GrimoireLab. Every **end-point view** must belong to one of these **data sources**. 

They are defined as the category of data we are retrieving from a **data end-point** from a particular **end-point view** (linking it to [Perceval](https://github.com/chaoss/grimoirelab-perceval) component, is the data which each of its backends is able to obtain).

For instance, from the same **data end-point** (for instance, a GitLab repository) we could have different **end-point views**, and each one could belong to a different **data source**:

* Git (to get the commit information from those repos).
* GitLab Issues.
* GitLab MRs.

## End-point views

An **end-point view** is a definition of the data which has to be retrieved from a given **data end-point**. This definition is composed by:
* The data source object which it belongs to.
* The filters, if any, specifying the data of interest (dates, elements, etc.).

By definition, a given **end-point** view cannot belong to more than one **project** or **ecosystem**.

## Projects

A **project** is defined as a group of **end-point views** (which belong to the corresponding **data sources** and can be heterogeneous) sharing a common context.

The projects can also have *n* sub-projects which also have sets of end-point views.

## Ecosystems

An **ecosystem** is defined as a set of **projects**. A **project** could belong to one single **ecosystem**, to different ones or not belonging to any project.

# WIP

The work in progress is to define and implement the fields for each of these entities and their relations with Django models.

I made a second version of a very basic sketch about the entities described above and how they could be related. Please note that it is only a sketch and it does not intend to show accurately the models, but a draft example of how the entities could be related with each other.

![bestiary2](https://user-images.githubusercontent.com/9032790/77343150-8c20b400-6d31-11ea-892f-eaf40339f1f2.png)

**Comment by sduenas** [comment]
I think this model might work but we need more time to evaluate. In any case, we agree the part of `Ecosystem` and `Projects` is what we want, so, I suggest to start working on that part and in the meantime we'll decide what to do with the other part of the model.

**Comment by jjmerchante** [comment]
# Update about Bestiary data model definition

`Projects` and `Ecosystems` are already implemented. From now the discussion will follow with data sources, and its relation with the projects and filters.

A project is defined as a group of data sources with categories and filters:

**DataSource**
This could be a Git repository, GitLab repository, StackExchange site, etc.
- **type**: ForeignKey to a table with all the supported data sources by Grimoirelab.
- **uri**: string

**DataSet**:
Define the data sources included for each project, category and filters.
- **project**: ForeignKey to project
- **data_source**:  ForeignKey to a data source
- **category**: String of the category of the analysis
- **filters**:  JSONField with filters for that data source

UNIQUE(project, data_source, category, filters)

Example of a data set:

|  Project | DataSource | Category | Filters | 
| ------------- | --- | --- | --- | 
| 1 |  2 | 'issues' | from_date | 
| 1 |  2 | 'pull-requests' |  | 
| 2 |  2 | 'pull-requests' |  | 
| 1 |  3 | 'commits' | branches: ['branch_1', 'branch_2'] | 
| 1 |  4 | 'questions' | tags: ['python'] | 
| 1 |  4 | 'questions' | tags: ['python', 'django'] |

**Comment by sduenas** [comment]
@jjmerchante let's try with that model. I think is a good beginning.
