### ISSUE TITLE
Implement GraphQL mutations for projects

### ISSUE THREAD

**Issue by mafesan** [chaoss/grimoirelab-bestiary#42]
The goal of this task is to implement basic mutations to manage **projects** (add, update, delete) and the query to get `Project` objects. 

As defined in #39:

* The projects can also have n sub-projects which also have sets of end-point views.
* A project could belong to one single ecosystem, to different ones or not belonging to any ecosystem.

**Comment by sduenas** [comment]
Fixed by #43 .
