### ISSUE TITLE
[ui] Implement Ecosystem tree component

### ISSUE THREAD

**Issue by evamillan** [chaoss/grimoirelab-bestiary#50]
This component will show the hierarchy of projects and sub projects nested inside an ecosystem. Each element of the tree will link to its corresponding page.

This is a mock-up of the component:
![imagen](https://user-images.githubusercontent.com/26812577/116578686-f2eba600-a911-11eb-92c9-af5816f4f999.png)

**Comment by zhquan** [comment]
Fixed by #51
