### ISSUE TITLE
[ui] Add projects from the UI

### ISSUE THREAD

**Issue by evamillan** [chaoss/grimoirelab-bestiary#52]
Users should be able to add new projects to an ecosystem by clicking a button on the sidebar. It should open a new page with a form that requests the project name, title and optional parent project.

Take the next mock-up as reference:
![imagen](https://user-images.githubusercontent.com/26812577/117299484-e2d74780-ae78-11eb-8291-15e724078797.png)

**Comment by sduenas** [comment]
Fixed by #53 .
